### ISSUE TITLE
Upgrading from 6.1.1 to 6.30.1 breaking chevron-down-icon

### ISSUE THREAD

**Issue by bandersongit** [zendeskgarden/svg-icons#224]
## Expectations
Previously was rendering as:
![image](https://user-images.githubusercontent.com/5252755/116276990-e57bc380-a739-11eb-892b-b9189e79aa5b.png)

actual generated HTML:
```<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" data-garden-id="buttons.icon" data-garden-version="3.9.10" class="index__c-btn__icon___3V0Rl"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="2" d="M4 6.5l3.6 3.6c.2.2.5.2.7 0L12 6.5"></path></svg>```

## Reality
Now renders as
![image](https://user-images.githubusercontent.com/5252755/116277051-f4627600-a739-11eb-8f47-57da0c3eac5f.png)
 actual generated HTML: 

```<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" data-garden-id="buttons.icon" data-garden-version="3.9.10" class="index__c-btn__icon___3V0Rl"><path fill="currentColor" d="M12.375 5.22a1 1 0 11.343 1.476 NaN NaNlNaN NaN NaN NaNa1 1 0 1-1.147 NaN NaNlNaN NaN NaN NaNa1 1 0 11.147-1.634 NaN NaNlNaN NaN NaN NaN NaN NaNz"></path></svg>```

## Steps to Reproduce

I understand the docs use inside an <IconButton>, we are not right now, but I tested with <IconButton> as well and was able to repro this behavior.

```
import ChevronDownFillIcon from "@zendeskgarden/svg-icons/src/16/chevron-down-fill.svg";

render() {

...
<ChevronDownFillIcon />
...
}
```

###### Fine Print
  - Browsers: all

**Comment by jzempel** [comment]
Seems like something is wrong with your build environment. As you can see from https://unpkg.com/browse/@zendeskgarden/svg-icons@6.30.1/src/16/chevron-down-fill.svg, the source is rendering as expected. Please reproduce the issue using [CodeSandbox](https://codesandbox.io/) and we'll take a closer look. Thanks.

**Comment by jzempel** [comment]
To add a bit more color, it seems your build process is attempting to perform a calculation whenever it enounters a `-` dash. See https://github.com/zendeskgarden/svg-icons/blob/v6.30.1/src/16/chevron-down-fill.svg?short_path=b900322

**Comment by bandersongit** [comment]
Thanks for the prompt response, I'll look into things further on my end!
