### ISSUE TITLE
SSR Support

### ISSUE THREAD

**Issue by PavlMais** [zendeskgarden/svg-icons#235]
## Expectations
Svg icons shows properly

## Reality
Error: Element type is invalid: expected a string (for built-in components) or a class/function
## Steps to Reproduce
[codesandbox](https://codesandbox.io/s/polished-butterfly-cfvdq?file=/pages/index.js
)
###### Fine Print

  - SVG: 
  - Browsers: all

**Comment by PavlMais** [comment]
Workaround:
```tsx 
<img src={(ChevronLeftIcon as any).src} alt="" />
```

**Comment by jzempel** [comment]
This is a matter of configuring your server environment with the ability to import SVGs as components. Garden recommends (and [uses](https://github.com/zendeskgarden/website/blob/49dc49f6c01d63962bc0e15cde044ad8e11fea1e/gatsby-config.js#L163-L177)) [SVGR](https://react-svgr.com/).

**Comment by PavlMais** [comment]
@jzempel It works, thanks
