### ISSUE TITLE
Need "alert-error-fill" icon with 14px size

### ISSUE THREAD

**Issue by ssidorchik** [zendeskgarden/svg-icons#25]
## Expectations

Hi Garden team. I have a use case for the `alert-error-fill` with 14px size.

## Reality

I see there are 300 icons with 12px and 16px sizes, but only 92 with 14px and there is no `alert-error-fill` among them. Could you please add the `alert-error-fill` icon with 14px size.

Is there any reason not to have some icons with 14px size?

###### Fine Print

  - SVG: 
  - Browsers: all

**Comment by jzempel** [comment]
Hi @ssidorchik. Our 14px icons are deprecated. Please consult with your designer and use either the 12 or 16px depending on requirements. Thanks!
