### ISSUE TITLE
ERROR: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by Keys147** [zendeskgarden/svg-icons#275]
## Expectations

Trying to use the svgs in my react components and I am getting this error.

**Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.**

## Steps to Reproduce

  1. Create a component as mentioned in README
```
import ZendeskIcon from '@zendeskgarden/svg-icons/src/26/zendesk.svg';

class ZendeskButton extends React.Component {
  render() {
    return (
      <button>
        <ZendeskIcon />
      </button>
    );
  }
}
```

Elsewhere, importing this and using it like` <ZendeskButton />` results in the above mentioned error. It is the same for any svg

**Comment by jzempel** [comment]
To be fair, it really depends on how your build pipeline is configured – and it would help if that were clarified in this README. For example, you can expand the code for this example to see code that works with CodeSandbox: https://garden.zendesk.com/components/avatar#shape
