### ISSUE TITLE
Suggestion: RTL mirroring metadata

### ISSUE THREAD

**Issue by aravindet** [zendeskgarden/svg-icons#63]
This is an enhancement request.

SVG icons should have some metadata (perhaps a class on the `<svg>` element?) that indicates whether the icon should be mirrored for RTL languages.

For example, an arrow that points left for "back" may need to be mirrored, while a logo may not.

**Comment by jzempel** [comment]
There's no reliably imperative way to know which SVGs must be mirrored. Here's why: we don't name SVGs according to function – rather we name them based on what they are. That means we don't necessarily control for exactly where they appear and how they operate. Consequently, a given SVG may need to mirror in some RTL contexts but might not in others.

An example, if a `play` icon were used for media, it should not be mirrored – the direction of "tape" is not affected by bidirectionality. However, if it were used to play back a sequence of events, it should be flipped – time based data is affected by bidirectionality.

Nice idea. But in most cases a human needs to be involved for making these choices.

p.s. this does raise an issue, though. We actually need two separate `list-number` SVGs – one for LTR and another for RTL. See https://material.io/design/usability/bidirectionality.html#localization for details.

/cc @ginnywood @allisonacs

**Comment by allisonacs** [comment]
Created https://zendesk.atlassian.net/browse/GARDEN-496 to address RTL `list-number` icon.

**Comment by jzempel** [comment]
Thanks @aravindet – closing as we're not able to address.
